EXEC dbo.pr_IATProvincia_Insertar "San José", NULL, NULL ;
EXEC dbo.pr_IATProvincia_Insertar "Alajuela", NULL, NULL;
EXEC dbo.pr_IATProvincia_Insertar "Cartago", NULL, NULL;
EXEC dbo.pr_IATProvincia_Insertar "Heredia", NULL, NULL;
EXEC dbo.pr_IATProvincia_Insertar "Guanacaste", NULL, NULL;
EXEC dbo.pr_IATProvincia_Insertar "Puntarenas", NULL, NULL;
EXEC dbo.pr_IATProvincia_Insertar "Limón", NULL, NULL;

EXEC dbo.pr_IATCanton_Insertar "San José", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Escazú", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Desamparados", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Puriscal", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Tarrazú", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Aserrí", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Goicoechea", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Santa Ana", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Alajuelita", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Vásquez de Coronado", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Acosta", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Tibás", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Moravia", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Montes de Oca", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Turrubares", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Dota", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Curridabat", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Pérez Zeledón", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "León Cortés", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Mora", 1, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Alajuela", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "San Ramón", 2, NULL, NULL
EXEC dbo.pr_IATCanton_Insertar "Grecia", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "San Mateo", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Atenas", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Naranjo", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Palmares", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Poás", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Orotina", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "San Carlos", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Zarcero", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Valverde Vega", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Upala", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Los Chiles", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Guatuso", 2, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Cartago", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Paraíso", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "La Unión", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Jiménez", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Turrialba", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Alvarado", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Oreamuno", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "El Guarco", 3, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Heredia", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Barva", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Santo Domingo", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Santa Bárbara", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "San Rafael", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "San Isidro", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Belén", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Flores", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "San Pablo", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Sarapiquí", 4, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Liberia", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Nicoya", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Santa Cruz", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Bagaces", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Carrillo", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Cañas", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Abangares", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Tilarán", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Nandayure", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "La Cruz", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Hojancha", 5, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Puntarenas", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Esparza", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Buenos Aires", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Montes de Oro", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Osa", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Aguirre", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Golfito", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Coto Brus", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Parrita", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Corredores", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Garabito", 6, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Limón", 7, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Pococí", 7, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Siquirres", 7, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Talamanca", 7, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Matina", 7, NULL, NULL;
EXEC dbo.pr_IATCanton_Insertar "Guácimo", 7, NULL, NULL;

EXEC dbo.pr_IATDistrito_Insertar "Carmen",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Merced",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Hospital",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Catedral",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Zapote",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Francisco de Dos Ríos",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Uruca",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mata Redonda",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pavas",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Hatillo",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Sebastián",1,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Escazú",2,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",2,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",2,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Desamparados",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Miguel",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan de Dios",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael Arriba",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Frailes",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Patarrá",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Cristóbal",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Rosario",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael Abajo",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Gravilias",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Los Guido",3,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santiago",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mercedes Sur",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Barbacoas",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Grifo Alto",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Candelarita",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Desamparaditos",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Chires",4,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Marcos",5,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Lorenzo",5,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Aserrí",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tarbaca",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Vuelta de Jorco",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Gabriel",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Legua",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Monterrey",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Salitrillos",6,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guadalupe",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Francisco",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Calle Blancos",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mata de Plátano",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Ipís",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Rancho Redondo",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Purral",7,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Ana",8,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Salitral",8,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pozos",8,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Uruca",8,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Piedades",8,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Brasil",8,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Alajuelita",9,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Josecito",9,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",9,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Concepción",9,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Felipe",9,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",10,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",10,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Dulce Nombre de Jesús",10,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Patalillo",10,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cascajal",10,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Ignacio",11,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guaitil",11,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmichal",11,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cangrejal",11,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sabanilas",11,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",12,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cinco Esquinas",12,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Anselmo Llorente",12,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "León XIII",12,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Colima",12,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Vicente",13,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Jerónimo",13,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Trinidad",13,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",14,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sabanilla",14,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mercedes",14,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",14,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pablo",15,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",15,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan de Mata",15,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Luis",15,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Carara",15,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa María",16,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jardín",16,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Copey",16,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Curridabat",17,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Granadilla",17,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sánchez",17,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tirrases",17,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro del General",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "El General",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Daniel Flores",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Rivas",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Platanares",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pejibaye",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cajón",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Barú",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Nuevo",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Páramo",18,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pablo",19,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Andrés",19,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Llano Bonito",19,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",19,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Cruz",19,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",19,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Ciudad Colón",20,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guayabo",20,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tabarcia",20,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Piedras Negras",20,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Picagres",20,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jaris",20,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Alajuela",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Carrizal",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guácima",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sabanilla",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Segundo",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Desamparados",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Turrúcares",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tambor",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Garita",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sarapiquí",21,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Ramón",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santiago",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Piedades Norte",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Piedades Sur",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Ángeles",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Alfaro",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Volio",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Concepción",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Zapotal",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Peñas Blancas",22,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Grecia",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Roque",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tacares",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Cuarto",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Puente de Piedra",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bolivar",23,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Mateo",24,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Desmonte",24,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jesús María",24,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Atenas",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jesús",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mercedes",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Concepción",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Eulalia",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Escobal",25,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Naranjo",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Miguel",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cirrí Sur",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Jerónimo",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "El Rosario",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmitos",26,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmares",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Zaragoza",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Buenos Aires",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santiago",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Candelaria",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Esquipulas",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Granja",27,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",28,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",28,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",28,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Carrillos",28,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sabana Redonda",28,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Orotina",29,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mastate",29,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Hacienda Vieja",29,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Coyolar",29,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Seiba",29,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Quesada",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Florencia",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Buena Vista",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Aguas Zarcas",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Venecia",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pital",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Fortuna",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Tigra",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Palmera",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Venado",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cutris",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Monterrey",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pocosol",30,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Zarcero",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Laguna",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tapezco",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guadalupe",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmira",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Zapote",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Brisas",31,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sarchí Norte",32,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sarchí Sur",32,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Toro Amarillo",32,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",32,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Rodríguez",32,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Upala",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Aguas Claras",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bijagua",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Delicias",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Dos Ríos",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Yolillal",33,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Los Chiles",34,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Caño Negro",34,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "El Amparo",34,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Jorge",34,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",35,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Buena Vista",35,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cote",35,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Katira",35,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Oriental",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Occidental",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Carmen",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Nicolás",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Agua Caliente",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guadalupe",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Corralillo",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tierra Blanca",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Dulce Nombre",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Llano Grande",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Quebradilla",36,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Paraíso",37,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santiago de Paraíso",37,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Orosi",37,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cachí",37,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Llanos de Santa Lucía",37,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tres Ríos",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Diego",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Concepción",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Dulce Nombre",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Ramón",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Azul",38,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Juan Viñas",39,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pejiballe",39,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Turrialba",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Suiza",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Peralta",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Cruz",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Tersita",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pavones",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tuis",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tayutic",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Rosa",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tres Equis",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Isabel",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Chirripó",40,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pacayas",41,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cervantes",41,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Capellades",41,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",42,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cot",42,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Potrero Cerrado",42,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cipreses",42,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Rosa",42,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tejar",43,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",43,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tobosi",43,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Patio de Agua",43,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Heredia",44,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mercedes",44,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Francisco",44,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Ulloa",44,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Varablanca",44,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Barva",45,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",45,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pablo",45,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Roque",45,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Lucía",45,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José e la Montaña",45,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santo Domingo",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Vicente",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Miguel",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Paracito",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santo Tomás",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Rosa",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tures",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pará",46,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Bárbara",47,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pedro",47,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",47,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jesús",47,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santo Domingo",47,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Purabá",47,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",48,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Josecito",48,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Satiago",48,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Ángeles",48,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Concepción",48,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",49,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San José",49,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Concepción",49,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Francisco",49,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",50,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Ribera",50,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Asunción",50,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Joaquín",51,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Barrantes",51,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Llorente",51,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pablo",52,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Rincón de Sabanilla",52,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Puerto Viejo",53,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Virgen",53,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Las Horquetas",53,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Llanureas del Gaspar",53,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cureña",53,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Liberia",54,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cañas Dulces",54,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mayorga",54,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Nacascolo",54,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Curubandé",54,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Nicoya",55,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mansión",55,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Antonio",55,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Quebrada Honda",55,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Nosara",55,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Belén de Nosarita",55,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Cruz",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bolsón",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Veintisiete de Abril",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tempate",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cartagena",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cuajiniquil",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Diriá",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cabo Velas",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tamarindo",56,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bagaces",57,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Fortuna",57,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mogote",57,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Naranjo",57,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Filadelfia",58,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmira",58,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sardinal",58,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Belén",58,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cañas",59,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmira",59,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Miguel",59,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bebedero",59,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Porozal",59,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Las Juntas",60,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sierra",60,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan",60,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Colorado",60,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tilarán",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Quebada Grande",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tronadora",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Rosa",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Líbano",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tierras Morenas",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Arenal",61,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Carmona",62,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Rita",62,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Zapotal",62,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Pablo",62,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Porvenir",62,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bejuco",62,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Cruz",63,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Cecilia",63,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Garita",63,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Santa Elena",63,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Hojancha",64,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Monte Romo",64,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Puerto Carrillo",64,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Huacas",64,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Puntarenas",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pitahaya",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Chomes",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Lepanto",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Paquera",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Manzanillo",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guacimal",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Barranca",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Monteverde",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Isla del Coco",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cóbano",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Chacarita",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Chira",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Acapulco",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "El Roble",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Arancibia",65,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Espíritu Santo",66,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Juan Grande",66,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Macacona",66,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Rafael",66,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Jerónimo",66,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Buenos Aires",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Volcán",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Potrero Grande",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Boruca",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pilas",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Colinas",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Chánguena",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Biolley",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Brunka",67,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Miramar",68,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Unión",68,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Isidro",68,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Puerto Cortés",69,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Palmar",69,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sierpe",69,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bahía Ballena",69,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Piedras Blancas",69,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Quepos",70,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Savegre",70,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Naranjito",70,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Golfito",71,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Puerto Jiménez",71,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guaycará",71,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pavón",71,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "San Vito",72,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sabalito",72,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Aguabuena",72,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Limoncito",72,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pittier",72,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Parrita",73,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Corredor",74,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "La Cuesta",74,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Paso Canoas",74,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Laurel",74,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jacó",75,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Tárcoles",75,NULL,NULL;

EXEC dbo.pr_IATDistrito_Insertar "Limón",75,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Valle la Estrella",75,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Blanco",75,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Matama",75,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guápiles",76,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Jiménez",76,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Rita",76,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Roxana",76,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cariari",76,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Colorado",76,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Siquirres",77,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pacuarito",77,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Florida",77,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Germania",77,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cairo",77,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Alegría",77,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Bratsi",78,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Sixaola",78,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Cahuita",78,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Telire",78,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Matina",79,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Batán",79,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Carrandi",79,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Guácimo",80,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Mercedes",80,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Pocora",80,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Río Jiménez",80,NULL,NULL;
EXEC dbo.pr_IATDistrito_Insertar "Duacarí",80,NULL,NULL;

EXEC dbo.pr_IATIdioma_Insertar "Inglés", NULL, NULL;
EXEC dbo.pr_IATIdioma_Insertar "Francés", NULL, NULL;
EXEC dbo.pr_IATIdioma_Insertar "Portugés", NULL, NULL;
EXEC dbo.pr_IATIdioma_Insertar "Mandarín", NULL, NULL;
EXEC dbo.pr_IATIdioma_Insertar "Otro", NULL, NULL;

EXEC dbo.pr_IATTipoContacto_Insertar "Tel Habitación", NULL, NULL;
EXEC dbo.pr_IATTipoContacto_Insertar "Tel Celular", NULL, NULL;
EXEC dbo.pr_IATTipoContacto_Insertar "Correo-E", NULL, NULL;

EXEC dbo.pr_IATTipoGuiaUso_Insertar "Documento", NULL, NULL;
EXEC dbo.pr_IATTipoGuiaUso_Insertar "Video", NULL, NULL;
EXEC dbo.pr_IATTipoGuiaUso_Insertar "Audio", NULL, NULL;

EXEC dbo.pr_IATTipoTrabajo_Insertar "Voluntariado", NULL, NULL;
EXEC dbo.pr_IATTipoTrabajo_Insertar "Remunerado", NULL, NULL;

EXEC dbo.pr_IATTipoUsuario_Insertar "Adulto Mayor", NULL, NULL;
EXEC dbo.pr_IATTipoUsuario_Insertar "Empresa", NULL, NULL;
EXEC dbo.pr_IATTipoUsuario_Insertar "Administrador", NULL, NULL;

EXEC dbo.pr_IATCategoriaTrabajo_Insertar "Administración", NULL, NULL;
EXEC dbo.pr_IATCategoriaTrabajo_Insertar "Ingeniería", NULL, NULL;
EXEC dbo.pr_IATCategoriaTrabajo_Insertar "Educación", NULL, NULL;
EXEC dbo.pr_IATCategoriaTrabajo_Insertar "Salud", NULL, NULL;

EXEC dbo.pr_IATUsuario_Insertar "administrador", "administrador", "blabla", 3, 1, NULL, NULL;